# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 22:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20171031_2121'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quotes',
            managers=[
                ('quotesManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
